### ISSUE TITLE
Chore: File uploading APIs

### ISSUE THREAD

**Issue by susalulmumaO12** [humam154/InternetApplications#1]
Need to finish logic for file uploading ASAP.

Trivial due date: 2024/12/19 11:59 pm

- [x] file upload
- [x] public folder path
- [x] validation for file update and download
- [x] file download
- [x] update file
- [x] request classes
- [x] array of files 
- [x] #6

**Comment by susalulmumaO12** [comment]
Almost done with file upload, without validation tho, any user with a token can upload a file, that should be resolved.

also, I have a problem, only absolute path for `public` folder is working, which is problematic, working on that...

**Comment by susalulmumaO12** [comment]
@humam154 please do me a favor and test it on Postman (Postman is broken on my end), I tested it with cURL, I need to see if it returns the expected response.

**Comment by susalulmumaO12** [comment]
File download is done, have not pushed it yet.

Will work on validation, new deadline: `validation | 2024/12/21 11:59 AM`

**Comment by susalulmumaO12** [comment]
Added a task: updating a file, uploading a file for the first time is different from updating one, as it needs to process some file checks.

**Comment by susalulmumaO12** [comment]
update and download file checks for in_use condition, what needs to be done:

- request classes for endpoints
- discussion on file checking

**Comment by ibra-kdbra** [comment]
Deadline was passed two times, `sheeeeesh`.

This is IT support, your **command**?

**Comment by susalulmumaO12** [comment]
This is a trivial deadline/s otherwise I don't know how to work, real deadline is 3 weeks ago
